# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: On se bouge
email: collectif@onsebouge.org
description: > # this means to ignore newlines until "baseurl:"
  *On se bouge* est un collectif d'habitants résidant sur un territoire allant de Vichy à Thiers, en passant par Châteldon. Il se donne comme objectif d'impulser des initiatives qui favorisent les rencontres et les actions collectives. Il propose à qui le veut des compétences de facilitation pour favoriser l'expression, l'écoute, la réflexion et l'action collective.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://onsebouge.org" # the base hostname & protocol for your site

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
future: true
